version: '2'

networks:
  fabric-ca:

services:
  ca-tls:
    container_name: ca-tls
    image: hyperledger/fabric-ca
    command: sh -c 'fabric-ca-server start -d -b tls-ca-admin:tls-ca-adminpw --port 7052'
    environment:
      - FABRIC_CA_SERVER_HOME=/home/wafa/production-network/fabric-ca/crypto
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=ca-tls
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - /home/wafa/production-network/tls/ca:/home/wafa/production-network/fabric-ca
    networks:
      - fabric-ca
    ports:
      - 7052:7052

  rca-org0:
    container_name: rca-org0
    image: hyperledger/fabric-ca
    command: /bin/bash -c 'fabric-ca-server start -d -b rca-org0-admin:rca-org0-adminpw --port 7053'
    environment:
      - FABRIC_CA_SERVER_HOME=/home/wafa/production-network/fabric-ca/crypto
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=rca-org0
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - /home/wafa/production-network/org0/ca:/home/wafa/production-network/fabric-ca
    networks:
      - fabric-ca
    ports:
      - 7053:7053

  rca-org1:
    container_name: rca-org1
    image: hyperledger/fabric-ca
    command: /bin/bash -c 'fabric-ca-server start -d -b rca-org1-admin:rca-org1-adminpw'
    environment:
      - FABRIC_CA_SERVER_HOME=/home/wafa/production-network/fabric-ca/crypto
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=rca-org1
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - /home/wafa/production-network/org1/ca:/home/wafa/production-network/fabric-ca
    networks:
      - fabric-ca
    ports:
      - 7054:7054

  rca-org2:
    container_name: rca-org2
    image: hyperledger/fabric-ca
    command: /bin/bash -c 'fabric-ca-server start -d -b rca-org2-admin:rca-org2-adminpw --port 7055'
    environment:
      - FABRIC_CA_SERVER_HOME=/home/wafa/production-network/fabric-ca/crypto
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=rca-org2
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - /home/wafa/production-network/org2/ca:/home/wafa/production-network/fabric-ca
    networks:
      - fabric-ca
    ports:
      - 7055:7055

  rca-org3:
    container_name: rca-org3
    image: hyperledger/fabric-ca
    command: /bin/bash -c 'fabric-ca-server start -d -b rca-org3-admin:rca-org3-adminpw --port 7056'
    environment:
      - FABRIC_CA_SERVER_HOME=/home/wafa/production-network/fabric-ca/crypto
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=rca-org3
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - /home/wafa/production-network/org3/ca:/home/wafa/production-network/fabric-ca
    networks:
      - fabric-ca
    ports:
      - 7056:7056

  rca-org4:
    container_name: rca-org4
    image: hyperledger/fabric-ca
    command: /bin/bash -c 'fabric-ca-server start -d -b rca-org4-admin:rca-org4-adminpw --port 7057'
    environment:
      - FABRIC_CA_SERVER_HOME=/home/wafa/production-network/fabric-ca/crypto
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=rca-org4
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - /home/wafa/production-network/org4/ca:/home/wafa/production-network/fabric-ca
    networks:
      - fabric-ca
    ports:
      - 7057:7057

  rca-org5:
    container_name: rca-org5
    image: hyperledger/fabric-ca
    command: /bin/bash -c 'fabric-ca-server start -d -b rca-org5-admin:rca-org5-adminpw --port 7058'
    environment:
      - FABRIC_CA_SERVER_HOME=/home/wafa/production-network/fabric-ca/crypto
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=rca-org5
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - /home/wafa/production-network/org5/ca:/home/wafa/production-network/fabric-ca
    networks:
      - fabric-ca
    ports:
      - 7058:7058

  peer1-org1:
    container_name: peer1-org1
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer1-org1
      - CORE_PEER_ADDRESS=peer1-org1:7051
      - CORE_PEER_LOCALMSPID=org1MSP
      - CORE_PEER_MSPCONFIGPATH=/home/wafa/production-network/org1/peer1/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=guide_fabric-ca
      - FABRIC_LOGGING_SPEC=debug
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/home/wafa/production-network/org1/peer1/tls/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/home/wafa/production-network/org1/peer1/tls/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/home/wafa/production-network/org1/peer1/tls/tlscacerts/tls-0-0-0-0-7052.pem
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1-org1:7051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
    working_dir: /home/wafa/production-network/working_dir/fabric/org1/peer1
    volumes:
      - /var/run:/host/var/run
      - /home/wafa/production-network/org1/peer1:/home/wafa/production-network/org1/peer1
    networks:
      - fabric-ca

  peer2-org1:
    container_name: peer2-org1
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer2-org1
      - CORE_PEER_ADDRESS=peer2-org1:7051
      - CORE_PEER_LOCALMSPID=org1MSP
      - CORE_PEER_MSPCONFIGPATH=/home/wafa/production-network/org1/peer2/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=guide_fabric-ca
      - FABRIC_LOGGING_SPEC=grpc=debug:info
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/home/wafa/production-network/org1/peer2/tls/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/home/wafa/production-network/org1/peer2/tls/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/home/wafa/production-network/org1/peer2/tls/tlscacerts/tls-0-0-0-0-7052.pem
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2-org1:7051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1-org1:7051
    working_dir: /home/wafa/production-network/working_dir/fabric/org1/peer2
    volumes:
      - /var/run:/host/var/run
      - /home/wafa/production-network/org1/peer2:/home/wafa/production-network/org1/peer2
    networks:
      - fabric-ca
      - /var/run:/host/var/run
      - /home/wafa/production-network/org1/peer2:/home/wafa/production-network/org1/peer2
    networks:
      - fabric-ca
  peer1-org2:
    container_name: peer1-org2
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer1-org2
      - CORE_PEER_ADDRESS=peer1-org2:7051
      - CORE_PEER_LOCALMSPID=org2MSP
      - CORE_PEER_MSPCONFIGPATH=/home/wafa/production-network/org2/peer1/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=guide_fabric-ca
      - FABRIC_LOGGING_SPEC=debug
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/home/wafa/production-network/org2/peer1/tls/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/home/wafa/production-network/org2/peer1/tls/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/home/wafa/production-network/org2/peer1/tls/tlscacerts/tls-0-0-0-0-7052.pem
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1-org2:7051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
    working_dir: /home/wafa/production-network/working_dir/fabric/org2/peer1
    volumes:
      - /var/run:/host/var/run
      - /home/wafa/production-network/org2/peer1:/home/wafa/production-network/org2/peer1
    networks:
      - fabric-ca
  peer2-org2:
    container_name: peer2-org2
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer2-org2
      - CORE_PEER_ADDRESS=peer2-org2:7051
      - CORE_PEER_LOCALMSPID=org2MSP
      - CORE_PEER_MSPCONFIGPATH=/home/wafa/production-network/org2/peer2/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=guide_fabric-ca
      - FABRIC_LOGGING_SPEC=debug
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/home/wafa/production-network/org2/peer2/tls/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/home/wafa/production-network/org2/peer2/tls/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/home/wafa/production-network/org2/peer2/tls/tlscacerts/tls-0-0-0-0-7052.pem
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2-org2:7051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
    working_dir: /home/wafa/production-network/working_dir/fabric/org2/peer2
    volumes:
      - /var/run:/host/var/run
      - /home/wafa/production-network/org2/peer2:/home/wafa/production-network/org2/peer2
    networks:
      - fabric-ca
  peer1-org3:
    container_name: peer1-org3
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer1-org3
      - CORE_PEER_ADDRESS=peer1-org3:7051
      - CORE_PEER_LOCALMSPID=org3MSP
      - CORE_PEER_MSPCONFIGPATH=/home/wafa/production-network/org3/peer1/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=guide_fabric-ca
      - FABRIC_LOGGING_SPEC=debug
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/home/wafa/production-network/org3/peer1/tls/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/home/wafa/production-network/org3/peer1/tls/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/home/wafa/production-network/org3/peer1/tls/tlscacerts/tls-0-0-0-0-7052.pem
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1-org3:7051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
    working_dir: /home/wafa/production-network/working_dir/fabric/org3/peer1
    volumes:
      - /var/run:/host/var/run
      - /home/wafa/production-network/org3/peer1:/home/wafa/production-network/org3/peer1
    networks:
      - fabric-ca

  peer2-org3:
    container_name: peer2-org3
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer2-org3
      - CORE_PEER_ADDRESS=peer2-org3:7051
      - CORE_PEER_LOCALMSPID=org3MSP
      - CORE_PEER_MSPCONFIGPATH=/home/wafa/production-network/org3/peer2/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=guide_fabric-ca
      - FABRIC_LOGGING_SPEC=debug
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/home/wafa/production-network/org3/peer2/tls/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/home/wafa/production-network/org3/peer2/tls/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/home/wafa/production-network/org3/peer2/tls/tlscacerts/tls-0-0-0-0-7052.pem
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2-org3:7051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
    working_dir: /home/wafa/production-network/working_dir/fabric/org3/peer2
    volumes:
      - /var/run:/host/var/run
      - /home/wafa/production-network/org3/peer2:/home/wafa/production-network/org3/peer2
    networks:
      - fabric-ca

  peer1-org4:
    container_name: peer1-org4
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer1-org4
      - CORE_PEER_ADDRESS=peer1-org4:7051
      - CORE_PEER_LOCALMSPID=org4MSP
      - CORE_PEER_MSPCONFIGPATH=/home/wafa/production-network/org4/peer1/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=guide_fabric-ca
      - FABRIC_LOGGING_SPEC=debug
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/home/wafa/production-network/org4/peer1/tls/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/home/wafa/production-network/org4/peer1/tls/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/home/wafa/production-network/org4/peer1/tls/tlscacerts/tls-0-0-0-0-7052.pem
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1-org4:7051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
    working_dir: /home/wafa/production-network/working_dir/fabric/org4/peer1
    volumes:
      - /var/run:/host/var/run
      - /home/wafa/production-network/org4/peer1:/home/wafa/production-network/org4/peer1
    networks:
      - fabric-ca

  peer2-org4:
    container_name: peer2-org4
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer2-org4
      - CORE_PEER_ADDRESS=peer2-org4:7051
      - CORE_PEER_LOCALMSPID=org4MSP
      - CORE_PEER_MSPCONFIGPATH=/home/wafa/production-network/org4/peer2/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=guide_fabric-ca
      - FABRIC_LOGGING_SPEC=debug
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/home/wafa/production-network/org4/peer2/tls/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/home/wafa/production-network/org4/peer2/tls/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/home/wafa/production-network/org4/peer2/tls/tlscacerts/tls-0-0-0-0-7052.pem
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2-org4:7051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
    working_dir: /home/wafa/production-network/working_dir/fabric/org4/peer2
    volumes:
      - /var/run:/host/var/run
      - /home/wafa/production-network/org4/peer2:/home/wafa/production-network/org4/peer2
    networks:
      - fabric-ca

  peer1-org5:
    container_name: peer1-org5
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer1-org5
      - CORE_PEER_ADDRESS=peer1-org5:7051
      - CORE_PEER_LOCALMSPID=org5MSP
      - CORE_PEER_MSPCONFIGPATH=/home/wafa/production-network/org5/peer1/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=guide_fabric-ca
      - FABRIC_LOGGING_SPEC=debug
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/home/wafa/production-network/org5/peer1/tls/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/home/wafa/production-network/org5/peer1/tls/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/home/wafa/production-network/org5/peer1/tls/tlscacerts/tls-0-0-0-0-7052.pem
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1-org5:7051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
    working_dir: /home/wafa/production-network/working_dir/fabric/org5/peer1
    volumes:
      - /var/run:/host/var/run
      - /home/wafa/production-network/org4/peer1:/home/wafa/production-network/org5/peer1
    networks:
      - fabric-ca

  peer2-org5:
    container_name: peer2-org5
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer2-org5
      - CORE_PEER_ADDRESS=peer2-org5:7051
      - CORE_PEER_LOCALMSPID=org5MSP
      - CORE_PEER_MSPCONFIGPATH=/home/wafa/production-network/org5/peer2/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=guide_fabric-ca
      - FABRIC_LOGGING_SPEC=debug
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/home/wafa/production-network/org5/peer2/tls/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/home/wafa/production-network/org5/peer2/tls/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/home/wafa/production-network/org5/peer2/tls/tlscacerts/tls-0-0-0-0-7052.pem
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2-org5:7051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
    working_dir: /home/wafa/production-network/working_dir/fabric/org5/peer2
    volumes:
      - /var/run:/host/var/run
      - /home/wafa/production-network/org4/peer2:/home/wafa/production-network/org5/peer2
    networks:
      - fabric-ca
